apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetapp
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: aspnetapp
        image: susuregistry.azurecr.io/dotnet-docker/aspnetapp:c11c775cb6de55a665139766d99a4fc5236aa6af
        ports:
        - containerPort: 80
